export const REG_USERS_REQ = "REG_USERS_REQ";
export const REG_USERS_RES = "REG_USERS_RES";
export const REG_USERS_ERROR = "REG_USERS_ERROR";
export const REG_RESET = "REG_RESET";

export const LOGIN_USERS_REQ = "LOGIN_USERS_REQ";
export const LOGIN_USERS_RES = "LOGIN_USERS_RES";
export const LOGIN_USERS_ERROR = "LOGIN_USERS_ERROR";
export const LOGIN_RESET = "LOGIN_RESET";

export const GET_HOME_PAGE_REQ = "GET_HOME_PAGE_REQ";
export const GET_HOME_PAGE_RES = "GET_HOME_PAGE_RES";
export const GET_HOME_PAGE_ERROR = "GET_HOME_PAGE_ERROR";

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const GET_USER_ARTICLES = "GET_USER_ARTICLES";
export const GET_USER_ARTICLES_ERROR = "GET_USER_ARTICLES_ERROR";
export const CLEAR_USER_ARTICLES = "CLEAR_USER_ARTICLES";

export const GET_USERS_REQ = "GET_USERS_REQ";
export const GET_USERS_RES = "GET_USERS_RES";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_RESET = "GET_USERS_RESET";

export const UPDATE_USERS_REQ = "UPDATE_USERS_REQ";
export const UPDATE_USERS_RES = "UPDATE_USERS_RES";
export const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR";
export const UPDATE_USERS_RESET = "UPDATE_USERS_RESET";